### ISSUE TITLE
Push notification for lesson completion didn’t display “+” characters

### ISSUE THREAD

**Issue by kenmhaggerty** [learn-co-curriculum/git-github-and-learn#7]
See attached screenshot.
![learn_bug_push_notification_missing_characters](https://cloud.githubusercontent.com/assets/2646968/12860476/b79a9fee-cc2a-11e5-9769-8514d569519a.png)

**Comment by AnnJohn** [comment]
hi @kenmhaggerty this looks like a technical issue. Could you please file a bug report- if you hover over your profile pic in Learn, you'll see a menu and there will be an option there to Report a Bug. Thanks.
